# Service for Dev environment
apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: dev
  labels:
    app: notes-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: notes-app
---
# Service for Test environment
apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: test
  labels:
    app: notes-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: notes-app
---
# Service for Production environment
apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: production
  labels:
    app: notes-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: notes-app
